name: Deploy to EC2
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test01
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          sudo su -
          echo "$SECRET_KEY" > secret_key
          chmod 400 secret_key
          ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd ../../var/www/html && git pull origin main"
